# Standard labels from github-labels repository
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "priority: critical"
  color: "b60205"
  description: "Critical priority - needs immediate attention"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority - should be addressed soon"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority - can be addressed when convenient"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority - normal priority level"

- name: "status: can't reproduce"
  color: "fec1c1"
  description: "Issue cannot be reproduced"

- name: "status: confirmed"
  color: "215cea"
  description: "Issue has been confirmed"

- name: "status: duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "status: needs information"
  color: "fef2c0"
  description: "More information is needed to proceed"

- name: "status: wont do/fix"
  color: "eeeeee"
  description: "This will not be worked on"

- name: "status: in progress"
  color: "fbca04"
  description: "Work is currently in progress"

- name: "status: blocked"
  color: "d73a4a"
  description: "Blocked by external dependencies"

- name: "status: ready for review"
  color: "0e8a16"
  description: "Ready for code review"

- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type: discussion"
  color: "d4c5f9"
  description: "General discussion or questions"

- name: "type: documentation"
  color: "006b75"
  description: "Documentation improvements or updates"

- name: "type: enhancement"
  color: "84b6eb"
  description: "Improvements to existing functionality"

- name: "type: epic"
  color: "3E4B9E"
  description: "A theme of work that contain sub-tasks"

- name: "type: feature request"
  color: "fbca04"
  description: "New feature or request"

- name: "type: question"
  color: "d876e3"
  description: "Further information is requested"

# Size estimation labels
- name: "size: xs"
  color: "3cbf00"
  description: "Extra small (1-2 hours)"

- name: "size: s"
  color: "5d9801"
  description: "Small (half day)"

- name: "size: m"
  color: "7fb800"
  description: "Medium (1-2 days)"

- name: "size: l"
  color: "9fcc00"
  description: "Large (3-5 days)"

- name: "size: xl"
  color: "bf9f00"
  description: "Extra large (1+ weeks)"

# Team-specific labels
- name: "team: backend"
  color: "1d76db"
  description: "Core backend APIs, services and data platforms powering the Grounds ecosystem"

- name: "team: game"
  color: "d73a4a"
  description: "Minecraft gameplay services, matchmaking, orchestration and server runtime"

- name: "team: ops"
  color: "0e8a16"
  description: "Infrastructure, CI/CD pipelines, observability, security & deployment automation"

- name: "team: web"
  color: "fbca04"
  description: "Frontend apps, dashboards and tools – including Cockpit admin panel and player interfaces"

# Additional conventional commit labels
- name: "commit: feat"
  color: "1d76db"
  description: "New feature (conventional commit)"

- name: "commit: fix"
  color: "d73a4a"
  description: "Bug fix (conventional commit)"

- name: "commit: docs"
  color: "006b75"
  description: "Documentation changes (conventional commit)"

- name: "commit: style"
  color: "fef2c0"
  description: "Code style changes (conventional commit)"

- name: "commit: refactor"
  color: "84b6eb"
  description: "Code refactoring (conventional commit)"

- name: "commit: perf"
  color: "0e8a16"
  description: "Performance improvements (conventional commit)"

- name: "commit: test"
  color: "d4c5f9"
  description: "Test changes (conventional commit)"

- name: "commit: chore"
  color: "cfd3d7"
  description: "Build/tooling changes (conventional commit)"

- name: "breaking change"
  color: "b60205"
  description: "Introduces breaking changes"

# Autorelease labels
- name: "autorelease: pending"
  color: "ededed"
  description: "Indicates a PR is waiting for an automated release"

- name: "autorelease: tagged"
  color: "26a641"
  description: "Indicates a PR has been included in an automated release"

- name: "autorelease: snapshot"
  color: "0969da"
  description: "Indicates a PR should trigger a snapshot release"
