name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "fix: [brief description]"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: bug-title
    attributes:
      label: 🐛 Bug Title
      description: A clear and concise title for the bug
      placeholder: "Brief description of the bug"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 📝 Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug in detail..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: "What should have happened instead?"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: "What actually happened?"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop screenshots here..."

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but workaround exists
        - High - Major functionality broken
        - Critical - System unusable
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12, Ubuntu 20.04]
        - Browser: [e.g. Chrome 91, Firefox 89, Safari 14]
        - Version: [e.g. 1.2.3]
        - Additional context...

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context about the problem here
      placeholder: "Any additional information that might be helpful..."
