name: 📚 Documentation
description: Request documentation improvements or report documentation issues
title: "docs: [brief description]"
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about the documentation issue or improvement.

  - type: input
    id: doc-title
    attributes:
      label: 📚 Documentation Title
      description: A clear and concise title for the documentation issue
      placeholder: "Brief description of the documentation issue"
    validations:
      required: true

  - type: textarea
    id: doc-description
    attributes:
      label: 📝 Description
      description: A clear and concise description of the documentation issue
      placeholder: "Describe the documentation issue in detail..."
    validations:
      required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: 📖 Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Outdated content
        - Broken links
        - Formatting issues
        - Other
    validations:
      required: true

  - type: textarea
    id: current-docs
    attributes:
      label: 📄 Current Documentation
      description: If applicable, describe what the current documentation says
      placeholder: "What does the current documentation say? (if any)"

  - type: textarea
    id: expected-docs
    attributes:
      label: ✅ Expected Documentation
      description: What should the documentation say instead?
      placeholder: "What should the documentation say or include?"

  - type: input
    id: doc-location
    attributes:
      label: 📍 Documentation Location
      description: Where is this documentation located? (URL, file path, section, etc.)
      placeholder: "e.g., /docs/getting-started.md, README.md, API docs section"

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context about the documentation issue here
      placeholder: "Any additional information that might be helpful..."
