name: ✨ Feature Request
description: Suggest an idea for this project
title: "feat: [brief description]"
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: input
    id: feature-title
    attributes:
      label: ✨ Feature Title
      description: A clear and concise title for the feature
      placeholder: "Brief description of the feature"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 📝 Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: "Describe the feature in detail..."
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve?
      placeholder: "What problem are you trying to solve? What's the current limitation?"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your proposed solution
      placeholder: "How would you like this feature to work?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "What other approaches have you considered?"

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 🎯 Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        - Use case 1: ...
        - Use case 2: ...
        - Use case 3: ...

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here
      placeholder: "Any additional information, mockups, or examples..."
